### ISSUE TITLE
Button ok not working on rails 5.1.1

### ISSUE THREAD

**Issue by cheesepaulo** [nicolasblanco/sweet-alert2-rails#3]
`TypeError: link.getAttribute is not a function[Learn More]`

**Comment by supairish** [comment]
@cheesepaulo I had the same problem.  It's because this gem only works if you're using jquery-ujs and not the new 5.1 default rails-ujs JS library.  It should probably state that better in the README now that jquery-ujs is no longer the default

**Comment by patrickoramah** [comment]
So... is this bug gonna fixed anytime soon?

**Comment by nicolasblanco** [comment]
I don't have time to make this plugin work with the new `rails_ujs` without the jQuery dependency. So if you have time, feel free to submit a PR.
Meanwhile just follow: https://github.com/nicolasblanco/sweet-alert2-rails/commit/f5a3d18a2f7ebd3675b4e57d5ff498f51642e691

**Comment by cheesepaulo** [comment]
Thanks @nicolasblanco :+1:
